In [1]:
import numpy as np
import pandas as pd


In [2]:
data = pd.read_csv(r"C:\Users\hello\Downloads\PhishingData.csv")

In [3]:
data.head()

having_IP_Address  URL_Length  Shortining_Service  having_At_Symbol  \
0                  1           1                   0                 0   
1                  0           1                   0                 0   
2                  0           0                   0                 0   
3                  0           0                   0                 0   
4                  0           0                   1                 0   

   double_slash_redirecting  Prefix_Suffix  having_Sub_Domain  SSLfinal_State  \
0                         1             -1                 -1              -1   
1                         0             -1                  0               1   
2                         0             -1                 -1              -1   
3                         0             -1                 -1              -1   
4                         0             -1                  1               1   

   Domain_registeration_length  Favicon  ...  popUpWidnow  Iframe  \
0                            0        0  ...            0       0   
1                            0        0  ...            0       0   
2                            0        0  ...            0       0   
3                            1        0  ...            0       0   
4                            0        0  ...            1       0   

   age_of_domain  DNSRecord  web_traffic  Page_Rank  Google_Index  \
0             -1          1           -1         -1             0   
1             -1          1            0         -1             0   
2              0          1            1         -1             0   
3             -1          1            1         -1             0   
4             -1          1            0         -1             0   

   Links_pointing_to_page  Statistical_report  Result  
0                       1                   1       1  
1                       1                   0       1  
2                       0                   1       1  
3                      -1                   0       1  
4                       1                   0       0  

[5 rows x 31 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2456 entries, 0 to 2455
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   having_IP_Address            2456 non-null   int64
 1   URL_Length                   2456 non-null   int64
 2   Shortining_Service           2456 non-null   int64
 3   having_At_Symbol             2456 non-null   int64
 4   double_slash_redirecting     2456 non-null   int64
 5   Prefix_Suffix                2456 non-null   int64
 6   having_Sub_Domain            2456 non-null   int64
 7   SSLfinal_State               2456 non-null   int64
 8   Domain_registeration_length  2456 non-null   int64
 9   Favicon                      2456 non-null   int64
 10  port                         2456 non-null   int64
 11  HTTPS_token                  2456 non-null   int64
 12  Request_URL                  2456 non-null   int64
 13  URL_of_Anchor                2456 non-null   int

In [5]:
#check if there is any null value
data.isnull().sum()

having_IP_Address              0
URL_Length                     0
Shortining_Service             0
having_At_Symbol               0
double_slash_redirecting       0
Prefix_Suffix                  0
having_Sub_Domain              0
SSLfinal_State                 0
Domain_registeration_length    0
Favicon                        0
port                           0
HTTPS_token                    0
Request_URL                    0
URL_of_Anchor                  0
Links_in_tags                  0
SFH                            0
Submitting_to_email            0
Abnormal_URL                   0
Redirect                       0
on_mouseover                   0
RightClick                     0
popUpWidnow                    0
Iframe                         0
age_of_domain                  0
DNSRecord                      0
web_traffic                    0
Page_Rank                      0
Google_Index                   0
Links_pointing_to_page         0
Statistical_report             0
Result    

## Train-Test Splitting 

In [6]:
from sklearn.model_selection import train_test_split


In [7]:
y = data['Result']
X= data.drop(['Result'], axis =1)
X.head()

having_IP_Address  URL_Length  Shortining_Service  having_At_Symbol  \
0                  1           1                   0                 0   
1                  0           1                   0                 0   
2                  0           0                   0                 0   
3                  0           0                   0                 0   
4                  0           0                   1                 0   

   double_slash_redirecting  Prefix_Suffix  having_Sub_Domain  SSLfinal_State  \
0                         1             -1                 -1              -1   
1                         0             -1                  0               1   
2                         0             -1                 -1              -1   
3                         0             -1                 -1              -1   
4                         0             -1                  1               1   

   Domain_registeration_length  Favicon  ...  RightClick  popUpWidnow  Iframe  \
0                            0        0  ...           0            0       0   
1                            0        0  ...           0            0       0   
2                            0        0  ...           0            0       0   
3                            1        0  ...           0            0       0   
4                            0        0  ...           0            1       0   

   age_of_domain  DNSRecord  web_traffic  Page_Rank  Google_Index  \
0             -1          1           -1         -1             0   
1             -1          1            0         -1             0   
2              0          1            1         -1             0   
3             -1          1            1         -1             0   
4             -1          1            0         -1             0   

   Links_pointing_to_page  Statistical_report  
0                       1                   1  
1                       1                   0  
2                       0                   1  
3                      -1                   0  
4                       1                   0  

[5 rows x 30 columns]

In [8]:
y.head()

0    1
1    1
2    1
3    1
4    0
Name: Result, dtype: int64

In [9]:
train_X, test_X, train_y, test_y = train_test_split(X,y, test_size=0.3, random_state=2)

In [10]:
print(train_X.shape)
print(train_y.shape)
print(test_X.shape)
print(test_y.shape)

(1719, 30)
(1719,)
(737, 30)
(737,)


## Model-1 Logistic Regression

In [11]:
from sklearn.linear_model import LogisticRegression
from matplotlib import pyplot as plt
import seaborn as sns
%matplotlib inline

In [12]:
LR= LogisticRegression()
model_1 = LR.fit(train_X,train_y)

In [13]:
LR_predict = model_1.predict(test_X)

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import plot_confusion_matrix

In [15]:
accuracy_score(LR_predict, test_y)

0.9565807327001357

In [16]:
print(classification_report(LR_predict, test_y))

              precision    recall  f1-score   support

           0       0.96      0.97      0.96       417
           1       0.96      0.94      0.95       320

    accuracy                           0.96       737
   macro avg       0.96      0.95      0.96       737
weighted avg       0.96      0.96      0.96       737



In [17]:
print(confusion_matrix(LR_predict, test_y))

[[404  13]
 [ 19 301]]


## Model_2 Decision Tree

In [18]:
from sklearn.tree import DecisionTreeClassifier

In [19]:
dtree= DecisionTreeClassifier()
model_2 = dtree.fit(train_X, train_y)
dtree_predict = model_2.predict(test_X)

In [20]:
accuracy_score(dtree_predict, test_y)

0.9715061058344641

In [21]:
print(classification_report(dtree_predict, test_y))

              precision    recall  f1-score   support

           0       0.97      0.98      0.97       416
           1       0.98      0.96      0.97       321

    accuracy                           0.97       737
   macro avg       0.97      0.97      0.97       737
weighted avg       0.97      0.97      0.97       737



In [22]:
print(confusion_matrix(dtree_predict, test_y))

[[409   7]
 [ 14 307]]


## Model_3 Random Forest Classifier

In [23]:
from sklearn.ensemble import RandomForestClassifier


In [24]:
RF= RandomForestClassifier()
model_3 = RF.fit(train_X, train_y)
RF_predict= model_3.predict(test_X)

In [25]:
accuracy_score(RF_predict, test_y)

0.9810040705563093

In [26]:
print(classification_report(RF_predict, test_y))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98       413
           1       0.99      0.96      0.98       324

    accuracy                           0.98       737
   macro avg       0.98      0.98      0.98       737
weighted avg       0.98      0.98      0.98       737



In [27]:
print(confusion_matrix(RF_predict, test_y))

[[411   2]
 [ 12 312]]


## Model_4 SVM Classifier

In [28]:
from sklearn.svm import SVC

In [29]:
svc= SVC()
model_4 = svc.fit(train_X, train_y)
svc_predict = model_4.predict(test_X)

In [30]:
accuracy_score(svc_predict, test_y)

0.966078697421981

In [31]:
print(classification_report(svc_predict, test_y))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97       420
           1       0.96      0.96      0.96       317

    accuracy                           0.97       737
   macro avg       0.97      0.96      0.97       737
weighted avg       0.97      0.97      0.97       737



In [32]:
print(confusion_matrix(svc_predict, test_y))

[[409  11]
 [ 14 303]]


## Model_5 XGBoost Classifier

In [33]:
from xgboost import XGBClassifier

In [34]:
xgb= XGBClassifier()
model_5 = xgb.fit(train_X, train_y)
xgb_predict = model_5.predict(test_X)

In [35]:
accuracy_score(xgb_predict, test_y)

0.9647218453188603

In [36]:
print(classification_report(xgb_predict, test_y))

              precision    recall  f1-score   support

           0       0.96      0.98      0.97       413
           1       0.97      0.94      0.96       324

    accuracy                           0.96       737
   macro avg       0.97      0.96      0.96       737
weighted avg       0.96      0.96      0.96       737



In [37]:
print(confusion_matrix(xgb_predict, test_y))

[[405   8]
 [ 18 306]]


## Comparision of models

In [38]:
print("LogisticRegression Accuracy:", accuracy_score(LR_predict, test_y), )
print("DecisionTree Classifier Accuracy:", accuracy_score(dtree_predict, test_y))
print("RandomForest Classifier Accuracy:", accuracy_score(RF_predict, test_y))
print("SVM Classifier Accuracy:", accuracy_score(svc_predict, test_y))
print("XGBoost Classifier Accuracy:", accuracy_score(xgb_predict, test_y))

LogisticRegression Accuracy: 0.9565807327001357
DecisionTree Classifier Accuracy: 0.9715061058344641
RandomForest Classifier Accuracy: 0.9810040705563093
SVM Classifier Accuracy: 0.966078697421981
XGBoost Classifier Accuracy: 0.9647218453188603


## We can see the accuracy of RandomForest is highest followed by DecisionTree and then SVM Classifier. Accuracy of Logistic Regression is lowest